### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AlbertArredondoAlfaro**
The purpose of this fork is to remove unnecessary singletons and make the code more simpler and easy to use.
The deallocs of ARController and PRARManager are now executed. Location services and events that are received from the accelerometer will also stop.

### CODE REVIEW

**Comment by xavierjurado** [comment]
This PR also solves a serious bug that causes the location manager to never stop asking for location/heading information.

**Comment by xavierjurado** [comment]
:+1:

**Comment by oriolpons** [comment]
Please :+1: :+1: :+1:

**Comment by rabenson** [comment]
:+1:

**Comment by glesage** [comment]
Wow hey my bad, I got a new job so I've got to get write access back to this so I can merge pulls, awesome job guys!

**Pull request merged**
